spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}:8848
        namespace: ${nacos.namespace}
    gateway:
      discovery:
        locator:
          # gateway可以通过开启以下配置来打开根据服务的serviceId来匹配路由
          lower-case-service-id: true
          # 是否可以通过其他服务的serviceId来转发到具体的服务实例。
          enabled: true
      routes:
        - id: auth
          uri: lb://mi-auth
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: authFallback
                fallbackUri: forward:/fallback/mi-auth/get
        - id: system
          uri: lb://mi-system-api
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                name: systemFallback
                fallbackUri: forward:/fallback/mi-system-api/get
        - id: goods
          uri: lb://mi-goods-api
          predicates:
            - Path=/goods/**
          filters:
            - name: Hystrix
              args:
                name: goodsFallback
                fallbackUri: forward:/fallback/mi-goods-api/get
      default-filters:
        - StripPrefix=1
  ## 排除mybatis-plus的自动装载
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

hystrix:
  command:
#    默认全局超时时间
    default:
      execution:
        tiemout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#    单个服务超时时间
#    systemFallback:
#      execution:
#        tiemout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 30000