spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}:8848
        namespace: ${nacos.namespace}
    gateway:
      discovery:
        locator:
          # gateway可以通过开启以下配置来打开根据服务的serviceId来匹配路由
          lower-case-service-id: true
          # 是否可以通过其他服务的serviceId来转发到具体的服务实例。
          enabled: true
      routes:
        - id: auth
          uri: lb://mi-auth
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: authFallback
                fallbackUri: forward:/fallback/mi-auth

