spring:
  # nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}:8848
        namespace: ${nacos.namespace}

  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 3
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 10000
    block-when-exhausted: true

  # 数据源配置
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/febs_cloud_txmanager?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8



tx-lcn:
  manager:
  # TM监听Socket端口.
    port: 9527
    # TM控制台密码
    admin-key: 123456